### ISSUE TITLE
add a `build.s2i.arch` configuration to be able to specify the architecture of the EAP S2I images

### ISSUE THREAD

**Issue by jmesnil** [jbossas/eap-charts#5]
**Is your feature request related to a problem? Please describe.**

EAP 7.4 provides images for Z-Series and PowerPC that are distinct from the x86 images.
The users must be able to specify they want to use these images.

**Describe the solution you'd like**

Add a `build.s2i.arch` property:

* type: `string`
* allowed values: `amd64` 
* default value: `amd64`

When the EAP 7.4 images for PPC and Z-Series are released, the constraint will be extended to:
* allowed values: `amd64, ppc64le, s390x`
* restriction: `ppc64le, s390x` are valid only when `build.s2i.jdk == 11`.

The actual builder and runtime images will be determined in the `eap74.eapBuilderImage` and  `eap74.eapRuntimeImage`
template functions.

The `value.yaml` will list all the available images:

```yaml
build:
  s2i:
    version: latest
    arch: "amd64"
    jdk: "11"
    amd64: 
      jdk8:
        builderImage: registry.redhat.io/jboss-eap-7-tech-preview/eap74-openjdk8-openshift-rhel7
        runtimeImage: registry.redhat.io/jboss-eap-7-tech-preview/eap74-openjdk8-runtime-openshift-rhel7
      jdk11:
        builderImage: registry.redhat.io/jboss-eap-7-tech-preview/eap74-openjdk11-openshift-rhel8
        runtimeImage: registry.redhat.io/jboss-eap-7-tech-preview/eap74-openjdk11-runtime-openshift-rhel8
```

When the EAP 7.4 images for PPC and Z-Series are released, they will be listed in `value.yaml`:

```yaml
build:
  s2i:
    ppc64le: 
      jdk11:
        builderImage: registry.redhat.io/jboss-eap-7-tech-preview/eap74-openj9-11-openshift-rhel8
        runtimeImage: registry.redhat.io/jboss-eap-7-tech-preview/eap74-openk9-11-runtime-openshift-rhel8
    s390x: 
      jdk11:
        builderImage: registry.redhat.io/jboss-eap-7-tech-preview/eap74-openj9-11-openshift-rhel8
        runtimeImage: registry.redhat.io/jboss-eap-7-tech-preview/eap74-openk9-11-runtime-openshift-rhel8
```
