### ISSUE TITLE
Ability to configure container/Pod scaling capability.

### ISSUE THREAD

**Issue by whitingjr** [jbossas/eap-charts#50]
**Is your feature request related to a problem? Please describe.**
I need to configure scaling. With a min and max.

**Describe the solution you'd like**
To configure somewhere the following

```
  - resource:
      name: cpu
      target:
        averageUtilization: 95
        type: Utilization
    type: Resource
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: foobar
```

**Describe alternatives you've considered**
Patching my resources after deploying to a container platform.
